### ISSUE TITLE
Irkorzik MT softlock & loc issues 

### ISSUE THREAD

**Issue by FantasticFwoosh** [JayBean/Anbennar-PublicFork#5]
### Issue Summary

Certain missions following on from the mission `An appropriate incentive` rely on a strict number of outcomes that are referenced dynamically in following missions like `a human pack` and `future of the pack`, making it not possible to begin the MT without forcing the player to interact with them.

If the tags have been conquered or had their overlordship broken, their loc referencing them is also broken amongst the mission rewards and criteria descriptions without targets.

![image](https://github.com/JayBean/Anbennar-PublicFork/assets/18471896/7e5a8b33-ff0f-4fec-b680-5ed89091a91a)

### Technical Details
version] (ver:Bitbucket (Up to date, 07/05/24 today's build))
exps: CoP,RoM,CoC,MoH,Gold-C,Emp,Levithn
submods: no

### Reproduction

- Play Irkorzik, conquer your neighbors and either annex/cancel subject the targets for `an appropriate incentive`, or have them be annexed/cancel subject by nearby AI nations.
- You will be softlocked from continuing the MT, without a overcomplicated process of somehow releasing/force vassalizing the tag and transferring ownership again to somebody which they may not want in the terms of a peacedeal. You cannot insult yourself to fufill the criteria `all of the following must be true:`
- After these first two steps, read the remainder of the mission criteria, and rewards with dynamically put in names, it will be annotated with `:` and `.`

### Recommended Action
Some workarounds would be welcome, between the technical fixes. Here are some propositions.

- `An appropriate incentive` : Mausujirad & Taafisi do not exist, or you own at least one of them as a vassal with less than 50% liberty desire.
- `The Human Pack` : Have any Fangualan human tag or Mausujira/Taafisi become a march with a specified amount of development & liberty desire, rewarding claims to your subjects, and a potential buff to maus/taafi.
- `Future of the Packs` : Own the land directly ( five specified regions in south Fangula) with similar reward to 'delusions of grandeur' for 10 years of sepratism.

### Additional Notes
Fanguala is a easy region to consolidate, which for my run was a higher agenda to move through the righthand side of the tree as quickly as possible before solving the religious missions, since its easier to harmonize tolerance with biakarta's legacy and ideagroups while expanding easy convert targets eastward. Which is a pity as this seemed like a fun tag.

**Comment by GoodNGS** [comment]
Hello! I'm the person that made Irkorzik's MT. Sorry for the delay, I didn't know someone posted an issue on GitHub. I was only paying attention to the things people brought up on the Discord server. I will take a closer look at your suggestions and fix these issues. Thanks a lot for bringing this up and sorry again for the delay.

**Comment by FantasticFwoosh** [comment]
fixed by [PR #7174](https://github.com/JayBean/Anbennar-PublicFork/commit/024fcc6f2c3a7564d4f392a2262eb4213142f66f)

Thanks GoodNGS and the Anbennar team.
